### PR TITLE
Refactor Kronos pipelines to be more modular

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
This pull request refactors the pipelines with more modular designs. It leverages Kronos' recent support for specifying "setup" and "samples" files separately from the pipeline. This features allows us to uncouple the samples from the pipeline. Additionally, we can now maintain setup files for different environments (_e.g._ genesis vs. gphosts vs. ARC queue). 

I want everyone to acknowledge this upcoming change to the repository before merging with master.

### CODE REVIEW

**Comment by ppararaj** [comment]
Acknowledged

**Comment by BrunoGrandePhD** [comment]
I'm testing the new modular TITAN pipeline on some samples. Any bug fixes are posted to this branch until it is merged into master.

**Comment by rdmorin** [comment]
Acknowledged

**Comment by ghost** [comment]
Acknowledged

**Comment by BrunoGrandePhD** [comment]
Alright, I will proceed with merging this pull request with master and tag it as version 3.0.

**Pull request merged**
