### PR TITLE
Revise the Realignment Pipeline

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
@ppararaj, we are going to use this pull request to track the discussion and revisions of the realignment pipeline before it is finalized. Unfortunately, due to the repetitive nature of Kronos configurations, the git diff'ing engine is having a hard time figuring out the additions and deletions. 

To add to this pull request, commit any changes to the `realign-revision` branch (see below). After pushing the updated `realign-revision`, the commit will automatically appear as part of this pull request. 

**Commit Changes to Pull Request:**

```
git fetch
git checkout realign-revision
# Perform changes
git add [...]
git commit -m [...]
git push origin realign-revision
```

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
I've organized the pipeline in "waves", which are sets of tasks that can be run independently of one another that all depend on the previous wave. I've sketched out the pipeline flow here: [Realignment Pipeline](https://github.com/morinlab/pipelines/files/76869/Realignment.Pipeline.Flow.pdf). Each wave is separated by a yellow line.

**Comment by BrunoGrandePhD** [comment]
I've also added bamUtil clipOverlap as the final BAM processing step.

**Comment by BrunoGrandePhD** [comment]
As described in the commit message for bc74f93, here's what I changed: 
- Improved spacing
- Improved dependencies and task flow
- Improved organization (now as "waves")
- Improved task names

**Comment by BrunoGrandePhD** [comment]
Another aspect I want to improve about the pipeline, if possible, is decreasing the number of attributes in the `SAMPLES` section. Many of these should be IO connections between tasks. I'm aware though that parallelization causes some complications with this. We'll try to find a workaround for most of these.

**Comment by BrunoGrandePhD** [comment]
I also want to move to a modular pipeline configuration by leveraging the latest features in Kronos. We can now specify a "samples" file and a "setup" file in addition to the standard configuration file, which would include the tasks. This way, we can easily run the exact same pipeline for different cohorts without having to change the tasks YAML file.

**Comment by ppararaj** [comment]
GATK Target Creator and Indel Aligner require a BAM index to run, although they can be run using the --unsafe parameter. Should I add an indexing task to the pipeline?

**Comment by BrunoGrandePhD** [comment]
@ppararaj I don't recall having to do that with the canine RNA-seq pipeline. Are you getting an error when running the pipeline?

**Comment by BrunoGrandePhD** [comment]
I'm going to tweak the `delete_files` component to take in an input directory and optionally, a file extension. This will make it compatible with our move towards using IO connections for the input/output directories.

**Comment by BrunoGrandePhD** [comment]
Here's a list of tweaks I want to incorporate into `delete_files`. 
1. I only want it to be able to delete files and not directories, as the name implies. 
2. I want to be able to specify an input directory. This would delete all files in that directory, but not sub-directories. 
3. For every deleted file, a new file with the same named appended by `.deleted` would be created, leaving a trace that the file existed.

**Comment by BrunoGrandePhD** [comment]
@ppararaj: At this [line](https://github.com/morinlab/pipelines/blob/bc74f93cafd2d2c7d4b03d3e7bfea1b9ca2e1da4/REALIGN/REALIGN.yaml#L148), shouldn't `new_fastqs` be under `input_files` and shouldn't there be `hash_sum_outfile` under `output_files`?

**Comment by BrunoGrandePhD** [comment]
I would also like to create a small component that compares two BamHash hash files and exits with status 0 if they match and non-zero if they don't.

**Comment by BrunoGrandePhD** [comment]
I've added a new output file for bam2fq in the pipeline in order to make everything work. Essentially, bam2fq needs to be able to output the interval file at a specified location.

**Comment by ppararaj** [comment]
I will change the hash read name script to output the hashsum of the new set of files and remove the part where it compares two hash sums.

**Comment by ppararaj** [comment]
I've altered hash_read_name.py with the new changes.

**Comment by BrunoGrandePhD** [comment]
@ppararaj will tweak hash_read_names to take in a directory and file pattern separately, allowing us to create IO connections.

**Comment by ppararaj** [comment]
Updated hash_read_names.py and corresponding component to now take directory and files separately as input.

**Comment by ppararaj** [comment]
Added 'interval_file' parameter to pysam_bam2fq.py and corresponding component. Users must now specify the location of the interval file.

**Comment by BrunoGrandePhD** [comment]
I've updated the pipeline to reflect the changes that were done to `delete_files` and `hash_read_names`.

@ppararaj, why did you disable the hash comparison check in `hash_read_names` when it is given a input hashsum in [this commit](https://github.com/morinlab/lab_scripts/commit/258018ef5c644e9c909ea3b9cd7f11ed82daf56b#diff-9bf9a7e9536a9ea88e2cd9db1a526b20)? We still need the script to exit with a non-zero status to stop the pipeline if the hashes don't match. Maybe you got confused when I mentioned that we needed a comparison components for BamHash, since it doesn't do the comparison itself.

**Comment by ppararaj** [comment]
Yeah I read that wrong. I've re-added the check.

**Comment by BrunoGrandePhD** [comment]
I think we are ready to test this pipeline before refactoring it to be modular. @ppararaj, could you run this pipeline on a small exome? Follow the instructions in the README for more details. Report back any issues; I expect a few bugs with all of the heavy edits. Feel free to fix the bugs and commit them back to this branch.

**Comment by BrunoGrandePhD** [comment]
I've rebased this branch on master and merged it into master.

**Pull request closed without merging**
